export enum ActionType {
  LOADING = "LOADING",
  ERROR = "ERROR",
  FETCH_TODOS = "FETCH_TODOS",
  CREATE_TODO = "CREATE_TODO",
  DELETE_TODO = "DELETE_TODO",
  UPDATE_TODO = "UPDATE_TODO",
  CLEAR_COMPLETED_TODOS = "CLEAR_COMPLETED_TODOS",
  TOGGLE_DARK_MODE = "TOGGLE_DARK_MODE",
  FILTER_TODOS = "FILTER_TODOS",
}
